// Generated by guri sync. Do not edit.
export interface RouteParams {
  "GET /": import("./types/src/routes/$types").Params;
  "GET /openapi.json": import("./types/src/routes/openapi.json/$types").Params;
  "GET /users": import("./types/src/routes/users/$types").Params;
  "POST /users": import("./types/src/routes/users/$types").Params;
  "GET /users/:id": import("./types/src/routes/users/[id]/$types").Params;
  "GET /users/:id/posts/:postId": import("./types/src/routes/users/[id]/posts/[postId]/$types").Params;
}
