// Generated by guri sync. Do not edit.
export type Params = {};
export type RouteParams = Params;
type Vars = (typeof import("../../../../../src/routes/+shared") extends { middleware: infer M } ? import("guri").InferStackVars<M> : {});
export type Middleware<Injects extends Record<string, unknown> = {}> =
  import("guri").Middleware<Params, import("guri").ValidatedInput, Injects>;
export type Handle<Input extends import("guri").ValidatedInput = import("guri").ValidatedInput> =
  import("guri").Handle<Params, Input, Vars>;
export type GET = import("guri").Handle<Params, import("guri").RouteInputOf<typeof import("../../../../../src/routes/openapi.json/+get")>, Vars & import("guri").MiddlewareVarsOf<typeof import("../../../../../src/routes/openapi.json/+get")>>;
