// Generated by guri sync. Do not edit.
declare global {
  namespace Giri {
    interface Register {
      app: typeof import("../../src/main") extends {
        init: (...args: any[]) => infer R;
      }
        ? Awaited<R>
        : Record<string, unknown>;
    }
  }
}
export {};
