import {
    composeMiddleware,
    createContext,
    createTypedResponse,
    defineMiddleware,
    isTypedResponse,
    stack,
    toResponse,
    typedResponseToResponse,
} from './context';
import type {
    GiriAdapter,
    GiriBodySchema,
    GiriInputSchema,
    GiriRouteRegistration,
    Handle,
    HttpMethod,
    Middleware,
    RouteInput,
    Services,
} from './types';
import {
    defineBodySchema,
    defineInputSchema,
    isGiriBodySchema,
    isGiriInputSchema,
    prepareRequestInput,
    resolveRouteInput,
} from './validation';

export {
    composeMiddleware,
    createContext,
    createTypedResponse,
    defineBodySchema,
    defineInputSchema,
    defineMiddleware,
    isGiriBodySchema,
    isGiriInputSchema,
    isTypedResponse,
    prepareRequestInput,
    stack,
    toResponse,
    typedResponseToResponse,
};
export type * from './types';

type AnyHandle = Handle<any, any, any>;
type AnyMiddleware = Middleware<any, any, any>;

export interface GiriRuntimeRouteModule {
    readonly handle: AnyHandle;
    readonly middleware?: AnyMiddleware | readonly AnyMiddleware[];
    readonly body?: GiriBodySchema;
    readonly query?: GiriInputSchema;
    readonly config?: {
        readonly skipInherited?: boolean;
    };
}

export interface GiriRuntimeSharedModule {
    readonly middleware?: AnyMiddleware | readonly AnyMiddleware[];
}

/**
 * A route descriptor generated by a host integration.
 *
 * `module` and every `shared` entry should be statically imported module namespaces so Vite and
 * other bundlers can discover the complete route graph.
 */
export interface GiriRuntimeRoute {
    readonly method: HttpMethod;
    readonly path: string;
    readonly module: GiriRuntimeRouteModule;
    readonly shared?: readonly GiriRuntimeSharedModule[];
}

export interface CreateGiriAppOptions<App> {
    /** The complete runtime adapter that owns the app, routing, request dispatch, and serving. */
    readonly adapter: GiriAdapter<App>;
    /** Statically imported route modules, normally emitted by a virtual module or code generator. */
    readonly routes: readonly GiriRuntimeRoute[];
    /** App-wide services to seed onto `c.app` for every registered route. */
    readonly services?: Services;
    /** Secret passed to the adapter for signed cookie support. */
    readonly cookieSecret?: string;
}

function normalizeRoutePath(path: string): string {
    if (!path.startsWith('/')) {
        throw new Error(`Giri runtime route paths must start with "/": ${path}`);
    }
    return path;
}

function normalizeMiddleware(
    value: AnyMiddleware | readonly AnyMiddleware[] | undefined,
    label: string,
): AnyMiddleware[] {
    if (value === undefined) {
        return [];
    }
    if (typeof value === 'function') {
        return [value];
    }
    if (!Array.isArray(value) || value.some((middleware) => typeof middleware !== 'function')) {
        throw new Error(`${label} middleware must be a function or an array of functions.`);
    }
    return [...value];
}

function routeRegistration(
    route: GiriRuntimeRoute,
    options: Pick<CreateGiriAppOptions<unknown>, 'services' | 'cookieSecret'>,
): GiriRouteRegistration {
    const path = normalizeRoutePath(route.path);
    if (!route.module || typeof route.module.handle !== 'function') {
        throw new Error(`${route.method} ${path}: route module must export a handle function.`);
    }

    const inherited = route.module.config?.skipInherited
        ? []
        : (route.shared ?? []).flatMap((shared, index) =>
            normalizeMiddleware(shared.middleware, `${route.method} ${path} shared[${index}]`),
        );
    const middleware = [
        ...inherited,
        ...normalizeMiddleware(route.module.middleware, `${route.method} ${path}`),
    ];

    return {
        method: route.method,
        path,
        handle: route.module.handle,
        middleware,
        input: resolveRouteInput([
            ...middleware.map((fn, index) => ({
                label: `${route.method} ${path} middleware[${index}]`,
                body: fn.body,
                query: fn.query,
            })),
            {
                label: `${route.method} ${path}`,
                body: route.module.body,
                query: route.module.query,
            },
        ]),
        services: options.services,
        cookieSecret: options.cookieSecret,
    };
}

/**
 * Construct a backend-native app and register Giri's generated route modules on it.
 *
 * Giri does not route requests here. The supplied adapter owns the runtime; this function is only
 * the portable composition step used by generated and virtual modules.
 */
export function createApp<App>(options: CreateGiriAppOptions<App>): App {
    if (!options.adapter || typeof options.adapter.createApp !== 'function') {
        throw new Error('Giri runtime requires an adapter with createApp().');
    }
    if (typeof options.adapter.register !== 'function') {
        throw new Error('Giri runtime requires an adapter with register().');
    }

    const registered = new Set<string>();
    const registrations = options.routes.map((route) => {
        const registration = routeRegistration(route, options);
        const key = `${registration.method} ${registration.path}`;
        if (registered.has(key)) {
            throw new Error(`Duplicate Giri runtime route: ${key}`);
        }
        registered.add(key);
        return registration;
    });

    const app = options.adapter.createApp();
    for (const registration of registrations) {
        options.adapter.register(app, registration);
    }

    return app;
}
